security:
    encoders:
        CryptoConseils\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
            fos_oauth: false                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|js)/
            security: false
        main:
            pattern: ^/
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN }