<?php

namespace CryptoConseils\BlogBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCommentPublished($published)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.published = :published')
            ->setParameter('published', $published)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findByIdAndCommentPublished($id, $published)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.published = :published')
            ->setParameter('published', $published)
            ->andWhere('a.id <= :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
