services:
    cryptoconseils_blog.antispam:
        class: CryptoConseils\BlogBundle\Antispam\CryptoConseilsAntispam

    cryptoconseils.blog.twig.antispam_extension:
        class: CryptoConseils\BlogBundle\Twig\AntispamExtension
        arguments:
         - "@cryptoconseils_blog.antispam"
        tags:
         - { name: twig.extension }

#    cryptoconseils_blog.form.ckeditor:
#        class: CryptoConseils\BlogBundle\Form\CkeditorType
#        tags:
#         - { name: form.type, alias: ckeditor }